### ISSUE TITLE
Does it support inheritance?

### ISSUE THREAD

**Issue by cyfex** [cbeck88/visit_struct#31]
Say, I have such code:
```#include "visit_struct_intrusive.hpp"
struct A {
  BEGIN_VISITABLES(A);
  VISITABLE(int, x);
  END_VISITABLES;
};

struct B:A {
  BEGIN_VISITABLES(B);
  VISITABLE(int, y)
  END_VISITABLES;
}
```
Does it work?

**Comment by cbeck88** [comment]
It depends on what you mean by "work", but if you are expecting that visiting B would cause it to visit both x and y, I don't think that it does. I think the way this would behave is, if you have a reference to a B, you are either visiting it as a B or as an A, and the type of the reference will determine which.

I think it would be possible to extend it to support that, but you would probably have to change the syntax `BEGIN_VISITABLES(B);` to `BEGIN_VISITABLES(B, A);` or something like this, so that the macro would know about `A`. I don't think the macro can detect the inheritance otherwise.
